#                MMMMMM
#           OMMMMMMMMMMM MM
#         MMM    MMMMM       MM
#       MM                     MM
#      MM                        M
#    MMM  MMMMMMMMMM  MMMMMMMMMM  MM
#    MM MMMMMMMMMMMMMM MMMMMMMMMMM M
#   MMM MM         MMMM        MMMM M
#   MMM M MMMMMM  M, MMM         MMM
#   MMM  M   MM MMMM  MMM MMMMMMMM
#   MMMM      MMMMM   8 MMMMMMMMMMMM
#    MMMMMMMMMMMM     MMMMM      MMMM
#    M MMMMMMMM  MMM MMMM MMMMMM  MMM
#   D,MMN        OMMM M   MMMMM MM,MM
#     MMMM8       MMMM8       8MMMMMM
#    M DMMMMMMMMMM$+MMMMMMMMMMMMM MM?
#     M= MMMMMMMMMM   MMMMMMMMM  MMM
#      M                        MMM
#       MM                     MM
#          MM       MMMM    MMM
#              MM MMMMMMMMMM
#                  MMMMM
#
#         ** auryn makefile **
#
# issues : https://github.com/aurynjs/auryn/issues
#

auryn_cli := {{aurynClientPath}}


android_bin_android := $(shell ${auryn_cli} config get android.bin.android -p ${project_path})
android_target := $(shell ${auryn_cli} config get android.target -p ${project_path})

ant_bin := $(shell ${auryn_cli} config get ant.bin -p ${project_path})

java_home := $(shell ${auryn_cli} config get java.home -p ${project_path})

project_path := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
project_appid := $(shell ${auryn_cli} config get project.appid -p ${project_path})
project_dockdir := $(shell ${auryn_cli} config get -t relpath project.dockdir -p ${project_path})
project_name := $(shell ${auryn_cli} config get -t oneword project.name -p ${project_path})


distclean:
	@rm -rf ${project_dockdir}

android-debug: ${project_dockdir}/android
	@JAVA_HOME=${java_home} ${ant_bin} -q -f ${project_dockdir}/android/build.xml debug

android-release: ${project_dockdir}/android
	@JAVA_HOME=${java_home} ${ant_bin} -q -f ${project_dockdir}/android/build.xml release

${project_dockdir}/android:
	@${android_bin_android} -s create project \
		--target ${android_target} \
		--name ${project_name} \
		--path ${project_dockdir}/android \
		--activity TempActivityName \
		--package ${project_appid}
	@${auryn_cli} autoconfigure \
		-p ${project_path} \
		--android-manifest ${project_dockdir}/android/AndroidManifest.xml
