#                MMMMMM
#           OMMMMMMMMMMM MM
#         MMM    MMMMM       MM
#       MM                     MM
#      MM                        M
#    MMM  MMMMMMMMMM  MMMMMMMMMM  MM
#    MM MMMMMMMMMMMMMM MMMMMMMMMMM M
#   MMM MM         MMMM        MMMM M
#   MMM M MMMMMM  M, MMM         MMM
#   MMM  M   MM MMMM  MMM MMMMMMMM
#   MMMM      MMMMM   8 MMMMMMMMMMMM
#    MMMMMMMMMMMM     MMMMM      MMMM
#    M MMMMMMMM  MMM MMMM MMMMMM  MMM
#   D,MMN        OMMM M   MMMMM MM,MM
#     MMMM8       MMMM8       8MMMMMM
#    M DMMMMMMMMMM$+MMMMMMMMMMMMM MM?
#     M= MMMMMMMMMM   MMMMMMMMM  MMM
#      M                        MMM
#       MM                     MM
#          MM       MMMM    MMM
#              MM MMMMMMMMMM
#                  MMMMM
#
#         ** auryn makefile **
#
# issues : https://github.com/aurynjs/auryn/issues
#

curdir := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))


# This generated line will work for you.
#
# If you're about to share this project,
# You should change it to :
#
# auryn_cli := $(shell which auryn)
#
# -> after making sure auryn is in your path

auryn_cli := {{aurynClientPath}}

# Functions

conf = $(shell ${auryn_cli} config get $1 -p ${curdir})

# Engine parameters

auryn_engine_path := $(call conf,auryn.engine.path)

# Project parameters

project_appid := $(call conf,project.appid)
project_dockdir := $(call conf,project.dockdir)
project_name := $(call conf,project.name)

# Android parameters

droid_bin_android := $(call conf,android.bin.android)
droid_target := $(call conf,android.target)

droid_templatedir := $(call conf,android.templatedir)
droid_templates := $(shell ls ${droid_templatedir}/*.java.hbs)
droid_sources_names := $(foreach t,${droid_templates},$(notdir $(subst java.hbs,java,$(t))))
droid_dock_sourcesdir := ${project_dockdir}/android/src/$(subst .,/,${project_appid})
droid_dock_sources := $(foreach n,${droid_sources_names},${droid_dock_sourcesdir}/$(n))


droid_jar_path := $(call conf,auryn.engine.android.jar.path)
droid_jar_files := $(shell ls ${droid_jar_path}/*.jar)
droid_jar_names := $(foreach l,${droid_jar_files},$(notdir $(l)))
droid_dock_jar := $(foreach l,${droid_jar_names},${project_dockdir}/android/libs/$(l))

droid_native_path := $(call conf,auryn.engine.android.native.path)
droid_native_dirs := $(shell ls ${droid_native_path}/)
droid_native_names := $(foreach l,${droid_native_dirs},$(notdir $(l)))

droid_dock_native := $(foreach l,${droid_native_names},${project_dockdir}/android/lib/$(l))
droid_dock_libs := ${droid_dock_jar} ${droid_dock_native}
droid_dock_manifest := ${project_dockdir}/android/AndroidManifest.xml


# Java parameters

ant_bin := $(call conf,ant.bin)
java_home := $(call conf,java.home)

# Utils

xed_bin := $(call conf,xed.bin)

all:
	@echo ${droid_dock_libs}

distclean:
	@rm -rf ${project_dockdir}

android-debug: android-dock
	@JAVA_HOME=${java_home} ${ant_bin} -q -f ${project_dockdir}/android/build.xml debug

android-release: android-dock
	@JAVA_HOME=${java_home} ${ant_bin} -q -f ${project_dockdir}/android/build.xml release

android-dock: ${project_dockdir}/android ${droid_dock_sources} ${droid_dock_libs}

${project_dockdir}/android/src/%.java:
	@mkdir -p $(dir $@)
	@${auryn_cli} render android/$(notdir $@).hbs $@ -p ${curdir}

${project_dockdir}/android/libs/%.jar:
	@mkdir -p $(dir $@)
	@cp ${auryn_engine_path}/android/$(notdir $@) $@

${project_dockdir}/android/lib/%:
	@mkdir -p $(dir $@)
	@cp -r ${auryn_engine_path}/android/native/libs/$(notdir $@) $@

${project_dockdir}/android:
	@${droid_bin_android} -s create project \
		--target ${droid_target} \
		--name ${project_name} \
		--path ${project_dockdir}/android \
		--activity TempActivityName \
		--package ${project_appid}
	@cat ${droid_dock_manifest} \
	| ${xed_bin} --selector="application" --attr="android:name" "AurynMainApplication" \
	| ${xed_bin} --selector="activity" --attr="android:name" ".AurynMainActivity" \
	> ${droid_dock_manifest}.out
	@mv ${droid_dock_manifest}.out ${droid_dock_manifest}
	@rm -rf ${project_dockdir}/android/src/*
